#85 Implement scan command
necst-telescope/necst pull request #106
Opened 2022-11-28 19:01 UTC by Kirby1717

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #85

2022-11-29 03:31 UTC, KaoruNishikawa requested changes

2022-11-29 03:31 UTC, KaoruNishikawa commented on necst/core/commander.py
> +                    time=time,
```suggestion
                    time=[time],
```

2022-11-29 03:31 UTC, KaoruNishikawa commented on necst/core/commander.py
> +                lat=[standby_lat, end[1]],
`standby_lon` は `standby_position` 関数によって `Quantity` 型で、`end` はユーザーによって `int | float` で与えられるように見えます。`Quantity` と `int` は [CoordCmdMsg の定義](https://necst-telescope.github.io/necst-msgs/msg/CoordCmdMsg.html) からエラーになるはずなので、以下のようなコードを書いて確認してください。

```python
from necst_msgs.msg import CoordCmdMsg
from astropy.units as u
try:
  CoordCmdMsg(lon=[1, 1])
except Exception as e:
  print(e)
try:
  CoordCmdMsg(lon=[3 * u.deg, 5 * u.deg])
except Exception as e:
  print(e)
```

2022-11-29 03:31 UTC, KaoruNishikawa commented on necst/core/commander.py
> +                    error_az ** 2 + error_el ** 2 < threshold[target] ** 2
```suggestion
                    error_az**2 + error_el**2 < threshold[target] ** 2
```

[Black](https://black.readthedocs.io/en/stable/) というコード整形ソフトを使っているため、変数名と冪乗演算子の間のスペースはエラーになります (右辺は変数名 `threshold` と演算子の間に辞書のキーワード指定 `[target]` が入っているため例外です)。
もしより良いフォーマット (整形ソフト) を見つけたら別のissueで提案してください。

2022-11-29 03:31 UTC, KaoruNishikawa commented on necst/ctrl/antenna/horizontal_coord.py
>          )  # TODO: Take weather data into account.
https://github.com/necst-telescope/neclib/pull/271 で `PathFinder.get_altaz` などが使えるように変更しました。そちらを使ってほしいです。

2022-11-29 16:44 UTC, Kirby1717 commented on necst/core/commander.py
> +                    error_az ** 2 + error_el ** 2 < threshold[target] ** 2
https://github.com/necst-telescope/internal/discussions/2
にて記載されている通りの VSCode 設定を行っていますが、なぜか空白ありにフォーマットされてしまっているようです（空白を消して Save しても、Save したときに勝手に空白が追加されてしまいます）。

Commit suggestion させていただきます。

2022-11-29 16:50 UTC, Kirby1717 commented on necst/core/commander.py
> +                    time=time,
ありがとうございます。変更し忘れていました。

2022-11-29 18:21 UTC, Kirby1717 commented on necst/core/commander.py
> +                lat=[standby_lat, end[1]],
ありがとうございます。
```python
standby_lon = float(standby_lon.value)
standby_lat = float(standby_lat.value)
```
で `standby_position` 関数の後に float 化することで対処したいと思います。
`end` に関しては
```python
...
end: Optional[Tuple[float, float]] = None,
...
```
で一応引数の型を float と指定しているので、問題ないと思います。

2022-11-30 01:43 UTC, KaoruNishikawa commented on necst/core/commander.py
> +                lat=[standby_lat, end[1]],
@Kirby1717 
`Commander` はユーザーが直接操作する可能性の高いプログラムなので、他のプログラムとの整合性をとれば型の不一致が起きないような性質のものではなく、ユーザーの入力を可能な限り適切な型に変換する機能を持っておく (あるいはプログラムに詳しくない人でもわかるようなエラーを表示する) 必要があります。

アンテナの大雑把な駆動指示を与えるとき、`end=[45.0, 30.0]` のような入力を強制するのは単に「不便なプログラム」なので `int` での座標指示が入力されたときにエラーにならない実装に変更してほしいです。

また、Python の型ヒントは実行時には無視され、自動での型変換や C プログラムのコンパイル時のような型チェックは行われないことに注意してください。
(型ヒントはこちらで修正しておきます)

2022-11-30 06:30 UTC, Kirby1717 commented on necst/core/commander.py
> +                lat=[standby_lat, end[1]],
確かに、ユーザビリティ（使いやすさ）を考えたらおっしゃる通りですね。
ありがとうございます。


> (型ヒントはこちらで修正しておきます)

分かりました。
具体的にどの引数がどのような型で入力される可能性があるのかによって実装が変わりますので、ぜひよろしくお願いします。

2022-11-30 09:31 UTC, Kirby1717 commented on necst/ctrl/antenna/horizontal_coord.py
>          )  # TODO: Take weather data into account.
https://github.com/necst-telescope/necst/pull/106/files/8a1394e9b8dc1d701101cb36cebd709c3f71b1b0#diff-5603d58bb0e44d24fa988f4a2da14a62ee67228c2fecae0780c71c148863530fR113-R123
こちらで `self.calculator` を使わず、`self.finder` に全て置き換えるという認識でよろしいでしょうか。
（"SCAN" コマンドだけでなく "POINT" コマンドにも `PathFinder` をしてよろしいのでしょうか。"SCAN" はともかく、"POINT" は Path を Find しているわけではないのでちょっと違和感がある気がするのですが…）

2022-12-02 04:13 UTC, KaoruNishikawa commented on necst/ctrl/antenna/horizontal_coord.py
>          )  # TODO: Take weather data into account.
`PathFinder` クラスは `CoordCalculator` クラスを継承しています。そのため両方をインスタンス化するのは純粋にリソースの無駄になります。
名前にこだわるなら `__init__` 関数内で `self.calculator = self.finder` と代入してください。

2022-12-02 05:25 UTC, Kirby1717 commented on necst/ctrl/antenna/horizontal_coord.py
>          )  # TODO: Take weather data into account.
リソースの無駄はおっしゃる通りですね。
では `self.calculator` の代わりに `self.finder` のみを利用するようにします。

2022-12-06 11:54 UTC, KaoruNishikawa requested changes

2022-12-06 11:54 UTC, KaoruNishikawa commented on necst/core/commander.py
> +            self.antenna("stop")
スキャンが始まった直後にアンテナが停止しているように見えるのは気のせいでしょうか？

2022-12-06 12:15 UTC, Kirby1717 commented on necst/core/commander.py
> +            self.antenna("stop")
該当位置の `wait` の実装を忘れていたので、実装しました。

2022-12-06 12:20 UTC, KaoruNishikawa requested changes

2022-12-06 12:20 UTC, KaoruNishikawa commented on necst/core/commander.py
> +                self.wait_convergence("antenna")
`SCAN` コマンドは `wait=False` でもスキャン駆動が可能な実装にしてほしいです。

2022-12-06 12:24 UTC, Kirby1717 commented on necst/core/commander.py
> +                self.wait_convergence("antenna")
申し訳ありません。`if wait:` を削除しました。

2022-12-06 18:33 UTC, merged