#164 Add conditional branch in Spectrometer
necst-telescope/necst pull request #167
Opened 2023-03-07 09:43 UTC by TatsumiISHIKAWA

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #...

2023-03-07 09:47 UTC, KaoruNishikawa requested changes
以下について確認をお願いします。

- 分光計のconfigがない場合、モジュールレベルのインポートがエラーになると思います。
  https://github.com/necst-telescope/necst/blob/37ffeb4380564f92741e923e41a4f6108ead6bfb/necst/rx/spectrometer.py#L11
- ログメッセージを正確な表現に修正してほしいです (何もシャットダウンしていないはず)

2023-03-07 10:37 UTC, TatsumiISHIKAWA commented
@KaoruNishikawa 
neclibのファイル位置が変更されたことによるエラーが出ています。現在このPull RequestはMerge先がMainになっていますが（僕がこの問題を失念していました）、HEMTの時と同様にMerge先を#156-recordに変更した方が良いでしょうか。

2023-03-07 12:57 UTC, KaoruNishikawa commented
@TatsumiISHIKAWA 
すぐに必要な機能ならマージ先を [#156-record](https://github.com/necst-telescope/necst/tree/%23156-record) に変更してください。#156 が解決するのを待ってもらっても大丈夫です。

2023-03-07 13:01 UTC, KaoruNishikawa commented on necst/rx/spectrometer.py
> +                "Spectrometer not found; no connection or no configuration"
同じような内容を繰り返しているので、以下のようなメッセージにしてほしいです。

```suggestion
                "Configuration for spectrometer not found; no spectral data would be recorded"
```

2023-03-09 01:33 UTC, TatsumiISHIKAWA commented
@KaoruNishikawa 
了解しました。今の所急ぎで実装する必要はなさそうなので #156 が解決され次第mergeすることにします。ありがとうございます。

2023-03-18 18:16 UTC, KaoruNishikawa approved these changes
Thanks for the contribution, LGTM!

2023-03-18 18:17 UTC, merged