#3 pid
necst-telescope/necst pull request #22
Opened 2022-09-06 16:40 UTC by KKnapier

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #3-PID

2022-09-06 16:58 UTC, KaoruNishikawa requested changes
@KKnapier 
コメントした箇所について修正をお願いします。

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.create_subscription_param(TimeFloat64, "pid_param",
各トピックに対応するメッセージ型は以下の通りです。
- speed : `TimedFloat64`
- pid_param : `PIDMsg`

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        calculator.error.push
`calculator` で計算した数値はどこにも使われていないので、この部分は不要です。

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.publisher.publish(TimeFloat64())
メッセージには `TimedFloat64(data=PIDの計算結果, time=time.time())` のようにして値を設定してください。

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.create_subscription_ang.append("altaz")
`create_subscription` の第3引数に設定する関数は `self, msg` の2つの引数をとるように実装してください。
`msg` からは `change_pid_param` 関数と同様にして値を取り出し、インスタンス変数に代入してください。
以上を実装すると次のようなコードになるはずです。

```python
def init_ang(self, msg):
    self.az = msg.lon
    self.el = msg.lat
    self.t = msg.time
```

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.create_subscription_enc.append("encorder")
`init_ang` 関数と同様に修正してみてください。

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +    def __init__(self, frequency: float) -> None:
`create_publisher` の第3引数は関数ではなく "history depth" で、整数を指定します。
また `create_subscription` の第4引数にも同様に整数を指定してください。
いずれも値は 1 で問題ありません。
https://docs.ros2.org/foxy/api/rclpy/api/node.html#rclpy.node.Node.create_publisher

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.command(0, "altaz")
`__init__` を修正するとこの関数は使われなくなるはずなので必要なければ削除してください。

2022-09-06 16:58 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +            time.sleep(0.05)
`self.command` 関数は定義されていません。ROS のレイヤではなくデバイスと直接通信をするプログラムで実装する機能なので削除してもらって大丈夫だと思います。

2022-09-07 01:49 UTC, KaoruNishikawa requested changes

2022-09-07 01:49 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +                                       self.change_pid_param, 1)
`create_subscription` という関数は [rclpy が定義](https://docs.ros2.org/foxy/api/rclpy/api/node.html#rclpy.node.Node.create_subscription) していますが、`create_subscription_and` という関数の定義は見当たりません。
関数名も変数の一種なので、定義されていない名前をいきなり使うことはできません。

また `create_publisher` の第3引数は history depth と呼ばれる整数型のパラメータで、"history depth" という文字列ではありません。以下のドキュメントを読んで修正してください。
https://docs.ros2.org/foxy/api/rclpy/api/node.html#rclpy.node.Node.create_publisher

2022-09-07 01:49 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.publisher.publish(TimedFloat64(speed, time.time()))
`speed` という変数は定義されていません。
変数を使うには以下のいずれかの方法で値を定義する必要があります。
- `変数名 = 値` の形で代入する
- `def 変数名():` の形で関数として定義する
- `class 変数名:` の形でクラスとして定義する
- `import 変数名` の形で他のファイルやパッケージから読み込む
明示的に定義していない変数 (`self.create_publisher` など) もありますが、これは [親クラス](https://docs.ros2.org/foxy/api/rclpy/api/node.html#module-rclpy.node) で定義されたものです。

2022-09-07 01:49 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.t = msg.time
指示値とエンコーダー値を同じ名前の変数に代入してしまうと後で区別できなくなります。

2022-09-07 01:49 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +            time.sleep(0.05)
このノードが処理を0.25秒の間 処理を止めても望遠鏡は止まりません。`self.publisher` から 0 という速度指示を送るようにするか、あるいは関数自体を削除してください。

2022-09-07 03:11 UTC, KaoruNishikawa requested changes

2022-09-07 03:11 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.publisher = self.create_publisher(TimedFloat64, "speed", QoSProfile, 1)
もう一度 [ドキュメント](https://docs.ros2.org/foxy/api/rclpy/api/node.html#rclpy.node.Node.create_publisher) を読んでください。`qos_profile (Union[QoSProfile, int])` は 「`qos_profile` というパラメータには `rclpy.qos.QoSProfile` のインスタンス、**または整数** を指定しなさい」という意味です。

2022-09-07 03:11 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +import history depth
history depth は変数ではなく「保持する履歴の数」という意味の一般的な説明です。

2022-09-07 03:11 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.publisher.publish(TimedFloat64("speed", time.time()))
`"speed"` は PID の計算結果でもなければ `float` 型の値でもありません。
この publisher から送信するのは PID の計算結果として得られる速度指示値です。

2022-09-07 03:11 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.t_enc = msg.time_enc
`"encoder"` トピックでやりとりされるデータは `CoordMsg` 型です。
メッセージファイル ([necst_msgs/msg/CoordMsg](https://github.com/necst-telescope/necst-msgs/blob/main/msg/CoordMsg.msg)) に定義されているパラメータ (`lon, lat, unit, frame, time, name`) から適切なものを選んで読み出してください。

2022-09-07 05:08 UTC, KaoruNishikawa requested changes
データ形式を改善できる気がしたので [necst-msgs](https://github.com/necst-telescope/necst-msgs) に以下のような変更をお願いします。
- `TimedAzElFloat64` を追加 (パラメータ : `az, el, time`)
- `PIDMsg` に `axis` パラメータを追加

2022-09-07 05:08 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.publisher.publish(TimedFloat64(self.speed(), time.time()))
```python
az_speed = self.controller["az"].get_speed(self.az, self.az_enc)
el_speed = self.controller["el"].get_speed(self.el, self.el_enc)
msg = TimedAzElFloat64(az=az_speed, el=el_speed, time=time.time())
self.publisher.publish(msg)
```

https://necst-telescope.github.io/neclib/_source/neclib.controllers.antenna_pid.html#neclib.controllers.antenna_pid.PIDController.get_speed

2022-09-07 05:08 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.controller = PIDController()
```python
self.controller = {
    "az": PIDController(),
    "el": PIDController(),
}
```

2022-09-07 05:08 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.controller.k_d = msg.k_d
```python
axis = msg.axis.lower()
self.controller[axis].k_p = msg.k_p
self.controller[axis].k_i = msg.k_i
self.controller[axis].k_d = msg.k_d
```

2022-09-07 06:28 UTC, KaoruNishikawa requested changes
以下にコメントした箇所が修正されていません。
- https://github.com/necst-telescope/necst/pull/22#discussion_r964306447
- https://github.com/necst-telescope/necst/pull/22#discussion_r964335833

テストコードを後ほど渡すので、それをマージした後にチェックが通るようデバッグしてください。

2022-09-08 12:04 UTC, KaoruNishikawa reviewed
@KKnapier 
テストコードを追加しました。
コード中の `import` に合わせてクラス名などの変更もお願いしたいです。
ノード名・名前空間などの設定は [Authorizer](https://github.com/necst-telescope/necst/blob/%2314-auth/necst/core/authorizer.py#L15) に合わせた実装にしてほしいです。

2022-09-08 13:51 UTC, KaoruNishikawa requested changes

2022-09-08 13:51 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +        self.create_subscription_param(PIDMsg, "pid_param",
以下にコメントした箇所を修正してください。

```python
self.create_subscription(PIDMsg, "pid_param", self.change_pid_param, 1)
```

https://github.com/necst-telescope/necst/pull/22#discussion_r964306447
https://github.com/necst-telescope/necst/pull/22#discussion_r964335833
https://github.com/necst-telescope/necst/pull/22#pullrequestreview-1098590223

2022-09-08 13:51 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +class config_PID(Node):
勉強会1、2回目の資料を見直してください。
このクラスをインポートしているのは以下のコードです。

https://github.com/necst-telescope/necst/blob/1e3452f58e5ff1def53d2f2dabe717cd3d0c0f4e/tests/ctrl/test_antenna_controller.py#L4

2022-09-08 13:51 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +    Namespace = f"/necst/{config.observatory}/core/controller"
Authorizer の意味を調べてください。

2022-09-08 13:51 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +    def __init__(self, frequency: float = 50):
クラス継承の方法を見直してください。

2022-09-08 13:51 UTC, KaoruNishikawa commented on necst/core/controller/antenna.py
> +    def init_ang(self, msg):
init は initialize (初期化) の略として使われる用語です。
この関数の機能をよりよく表現する名前に変更してください。

2022-09-09 05:55 UTC, KaoruNishikawa requested changes
「解決」扱いにしていない以下のコメントについて修正をお願いします。

https://github.com/necst-telescope/necst/pull/22#discussion_r964306447
https://github.com/necst-telescope/necst/pull/22#discussion_r964335833
https://github.com/necst-telescope/necst/pull/22#pullrequestreview-1098590223
https://github.com/necst-telescope/necst/pull/22#discussion_r965987728
https://github.com/necst-telescope/necst/pull/22#discussion_r965995776

次に以下のページでテストが通っていない原因を確認し、修正してください。
`antenna.py` を修正することでテストコードがエラーなく実行できることは確認してあります。

https://github.com/necst-telescope/necst/runs/8263892433?check_suite_focus=true

2022-09-09 16:16 UTC, KKnapier commented
まだテスト通っていないですがコード自体が合っている確証がないので一旦レビューリクエストします

2022-09-10 00:37 UTC, KaoruNishikawa requested changes

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/__init__.py
> +from necst import AntennaController
不要です。

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/core/__init__.py
> +from .. import AntennaController
不要です。

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/core/controller/AntennaController.py
> +from neclib.controllers import PIDController
このファイルを `necst/ctrl/antenna/controller.py` に移動・ファイル名変更してください。

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/core/controller/AntennaController.py
> +class AntennaController(Node, Authorizer):
`Authorizer` は継承しないでください。

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/core/controller/__init__.py
> +import AntennaController
不要です。

2022-09-10 00:37 UTC, KaoruNishikawa commented on necst/ctrl/__init__.py
> +from core import AntennaController
`from .controller import AntennaController`

この下に `controller` ディレクトリを作り、そこにも `__init__.py` を作成してください。

2022-09-10 00:37 UTC, KaoruNishikawa commented on tests/__init__.py
> +from .necst import AntennaController
不要です。

2022-09-10 00:37 UTC, KaoruNishikawa commented on tests/ctrl/__init__.py
> +import AntennaController
不要です。

2022-09-12 08:08 UTC, KaoruNishikawa requested changes
[エラー](https://github.com/necst-telescope/necst/runs/8300214124?check_suite_focus=true) を参照し、デバッグをしてください。

2022-09-13 21:31 UTC, KaoruNishikawa approved these changes
時刻を考慮しないと正確な制御ができませんが、これは <https://github.com/necst-telescope/necst/issues/29> での対応とします。

2022-09-13 21:32 UTC, merged