[WIP] #226 change necst to new version
necst-telescope/necst pull request #230
Opened 2023-10-17 16:45 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #226

2023-10-31 10:13 UTC, TatsumiISHIKAWA commented
@takayama-27 
Direct modeが反映された`neclib`バージョンがリリースされました。
DockerFileのneclibバージョンを0.24.11に変更してテストを再度回してください。

2023-11-07 08:46 UTC, TatsumiISHIKAWA commented
@TakutoIto @takayama-27 
neclibのversion 0.24.12がpypiに上がったことを確認しました。
以前と同じようにDockerFileのneclib versionを書き換えてテストを回し直してください

2023-11-07 10:22 UTC, r-yamada1998 requested changes
お疲れ様さまでした。全体的に良くできていると思います。
一点だけコメントです。デフォルト値falseがいくつかの関数の中で与えられていますが、デフォルト値はcomannderだけで与えて、他はcommanderから発出されたdirect_modeの値を読み取るというふうに仕様変更できませんか？
色々なところでデフォルト値を入れるのはバグの温床になりかねません。

2023-11-13 11:45 UTC, r-yamada1998 approved these changes
LGTM!!

2023-11-13 11:46 UTC, merged