Implement the optical pointing
necst-telescope/necst pull request #231
Opened 2023-10-27 13:10 UTC by Kirby1717

**Checks**

- [x] Debugging completed
- [ ] Please debug me

**Related Issue**

This PR closes #222.

2023-10-27 16:17 UTC, TatsumiISHIKAWA requested changes
修正をお願いします。

2023-10-27 16:17 UTC, TatsumiISHIKAWA commented on necst/procedures/observations/optical_pointing.py
> +        #     f"Starting Optical Pointing Observation. Estimated observing time is {estimated_time} min."
Flake8のCode Formatterのエラーです。まずこの行が文字数制限を超えているとのことです。このまま消してもいいのですが、将来的に観測完了予定時間の追加はしても良いと思いますのでTODOとしてください。
```suggestion
        # TODO: Add time estimator before observing.
```

2023-10-27 16:17 UTC, TatsumiISHIKAWA commented on necst/rx/ccd.py
> +from ..core import DeviceNode
次にimportが余分だとされています。
testのエラーを見てもらえればいいですが、このNodeのコード内では確かにtimeとconfigが使われていないので削除しておいてください。
```suggestion
from neclib.devices import CcdController as CCD_Device
from necst_msgs.msg import CCDMsg

from ... import namespace, topic
from ..core import DeviceNode
```

2023-10-29 07:13 UTC, TatsumiISHIKAWA commented
@Kirby1717 
よく考えたら光学ポインティングのneclibコードはまたリリースされていないのでテストに反映できないですね。
エラーを吐くのも納得です。neclibをリリースしたらこちらも上手くと思われるのでそれまでこっちは保留します。

2023-10-29 07:15 UTC, Kirby1717 commented
ですよね、丁度全く同じこと思いました笑
neclib が更新されたら改めてレビューお願いします。

2023-10-31 10:21 UTC, TatsumiISHIKAWA commented
@Kirby1717 
https://github.com/necst-telescope/necst/blob/432d6e08a709bdc077593e895ede5f1f85255f90/Dockerfile#L14-L19

Direct modeが反映されたneclibバージョンがリリースされました。
DockerFileのneclibバージョンを0.24.11に変更してテストを再度回してください。

```DockerFile
 RUN ( cd $ROS2_WS/src/necst && pip install "neclib==0.24.11" && pip install ipython ) 
```

2023-11-01 04:55 UTC, TatsumiISHIKAWA commented
@Kirby1717 
変更とテストありがとうございます。
テストが終わらないという問題がありますが、これはDirect Modeのテストの実装の不具合によるもののようです。
現在別のPR ( https://github.com/necst-telescope/necst/pull/230 ) でテストコードを修正することで対処中のようなのでそちらが終わり、Mergeされ次第mainからOpitical PointingのブランチにMergeしたあと、再度テストを回し直しましょう。

2023-11-07 09:12 UTC, TatsumiISHIKAWA requested changes
`necst/rx/__init__.py`内にccdのimportがないようです。
追記し、次の内容も修正の上でテストを回し直してください。

2023-11-08 09:47 UTC, TatsumiISHIKAWA requested changes
TESTのエラーコードを見る限り各種rxノードのimportに失敗しているようです。CCD以外も失敗していることが気にかかりますが、少なくともrx/ccdのclass名を直前のcommitで変更したことが一因のはずです。
necst/executors/ccd内でのimport名と内部の呼び出し名をnecst/rx/ccdでのclass名に合わせて変更してください。

2023-11-10 04:35 UTC, merged