#320 modi config saving
necst-telescope/necst pull request #321
Opened 2024-08-30 07:05 UTC by TatsumiISHIKAWA

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #320

2024-08-31 07:13 UTC, FumikaDemachi commented on necst/procedures/measurement/measurement_base.py
> +            self.telescope = os.environ.get("TELESCOP")
”TELESCOPE”

2024-08-31 07:13 UTC, FumikaDemachi commented on necst/procedures/observation_base.py
> +            self.telescope = os.environ.get("TELESCOP")
”TELESCOPE”

2024-08-31 07:14 UTC, FumikaDemachi requested changes
TELESCOP"E”

2024-09-03 00:39 UTC, FumikaDemachi commented on necst/procedures/measurement/measurement_base.py
> +    def run(self, *args, **kwargs) -> None: ...
```
    def run(self, *args, **kwargs) -> None:
        ...
```
3点リーダー改行してください

2024-09-03 00:39 UTC, FumikaDemachi commented on necst/procedures/observation_base.py
> +    def run(self, *args, **kwargs) -> None: ...
```
    def run(self, *args, **kwargs) -> None:
        ...
```
3点リーダ改行してください

2024-09-03 00:40 UTC, FumikaDemachi requested changes
フォーマットの修正お願いします

2024-09-14 17:44 UTC, TatsumiISHIKAWA commented
@FumikaDemachi 
このFlake8（もしくはBlack）のCode FormatはおそらくCode Formatterの更新によるルールの変更による新しい書き方だと思うのですが...この変更は必須ですか？
neclibでは常にFlake8とBlackの新バージョンが出次第新しいルールが適用されるようになっているのですが、necstは手動更新でした。つまり、VSCode上のFlake8, Blackの新しいルールと、TESTコード上の古いバージョンのFlake8, Blackのルールと合わなかったのが原因でTESTが通らなのが問題だったので修正したのがこのISSUEの趣旨です。

ちなみにこの開業のルールはneclibでは既に反映されている変更です。
https://github.com/necst-telescope/neclib/commit/f60731f62ac2fbccbfc0b6c7f995f8b56a71108b

2024-09-16 02:40 UTC, takayama-27 approved these changes
LTGM！

2024-09-16 02:41 UTC, merged