add test_sim_devices.py
necst-telescope/necst pull request #54
Opened 2022-09-29 03:06 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #...

2022-09-29 07:34 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +from base64 import encode
これは使わないので削除してください。

2022-09-29 07:41 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        enc = self.node.create_publisher(CoordMsg, f"{ns}/encoder", qos.realtime)
AntennaDeviceSimulator は speed を受け取って encoder 値を publish するので、ここでは speed を与えてあげる必要があります。
メッセージ型を`TimedAzElFloat64`にしてください。

2022-09-29 07:50 UTC, FumikaDemachi requested changes
@takayama-27 
コメントした箇所の修正をお願いします。

2022-10-01 09:09 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        enc = self.node.create_publisher(CoordMsg, f"{ns}/encoder", qos.realtime)
@takayama-27 
このtestはAntennaDeviceSimulator の動作を test するためのものです。
AntennaDeviceSimulatorの中身を見てみると、以下の部分でantenna_simulatorがコールバックとして使われています。
[https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/sim_devices.py#L19-L21](url)
antenna_simulatorはspeedの情報(メッセージ)を受け取ってコマンドを送り、encoder値をpublishしています。
[https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/sim_devices.py#L24-L33](url)

つまり、testコードではantenna_simulatorを動かすために、適当な速度を与えてあげる必要があります。
ですので、まずはpublishするメッセージの型を`TimedAzElFloat64`にしましょう。

2022-10-01 09:22 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            enc.publish(CoordMsg(lon=25.0, lat=45.0))
@takayama-27 
参考に示した以下のtestコードは、AntennaPIDControllerのテストです。
[https://github.com/necst-telescope/necst/blob/main/tests/ctrl/test_antenna_controller.py](url)
AntennaPIDControllerは座標を受け取って、speedをpublishするものです。
つまり、今書いているtestはこれの逆の動きになります。
ですので、publishするのはspeedの値にしましょう。

2022-10-01 09:27 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +                el_condition = (encoder_el is not None) and (encoder == 0)
ここではencoder_azとencoder_elの評価をしましょう。

2022-10-01 09:29 UTC, FumikaDemachi requested changes
@takayama-27 
コメントした部分について修正をお願いします。
speedを与えて、受け取ったencoder値を評価する、という流れであることを確認してください。

2022-10-01 15:51 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            cmd.publish(TimedAzElFloat64(speed=20.0))
az, el両方に対してspeedの値を入れてください。

2022-10-01 15:58 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +                el_condition = (encoder_el is not None) and (encoder_el == 0)
encoder_azはエンコーダーの値なので、その数字自体が>0か<0かを評価するのではなく、
与えた速度に対して適切なエンコーダーの値の変位になっているかを評価する必要があるかと思います。

2022-10-01 16:02 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +from turtle import speed
これは使わないので削除してください。

2022-10-01 16:07 UTC, FumikaDemachi requested changes
@takayama-27 
コメント部分の修正をお願いします。

2022-10-03 08:02 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        enc_el = enc.command(10.0, "el")
`AntennaDeviceSimulator`の方で指示を送るので、testコードでは必要ないです。

2022-10-05 00:46 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            sub
ここに書く必要はないので削除してください。

2022-10-05 00:51 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            encoder_el1 = msg.lat
update関数は一つで良いです。
メッセージが流れくる度にlistにappendするなどしてみてはいかがでしょうか。

2022-10-05 00:52 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            cmd.publish(TimedAzElFloat64(az=10.0, el=10.0))
ここで与える速度の単位はdegree/sらしいです。2 deg/sくらいを設定しましょう。

2022-10-05 00:57 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +                time.sleep(0.02)
シミュレーターの動き始めはゆっくりで、すぐには指示した速度では動けません。実機も同様です。
ですので、移動できたかの評価をする前に1sほどtime.sleepしておきましょう。

2022-10-05 01:03 UTC, FumikaDemachi requested changes
コメントした部分の修正をお願いします。

2022-10-05 04:48 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +from pyrsistent import l
これはいらないので削除してください。

2022-10-05 05:42 UTC, FumikaDemachi requested changes
コメント部分の修正をお願いします。

2022-10-07 07:35 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        encoder_az = encoder_el = None
l_az, l_elにappendしているので、値をアップデートする必要はありません。
こちらは削除してください。

2022-10-07 07:35 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +            encoder_el = msg.lat
l_az, l_elにappendしているので、一つの値を評価する必要はありません。
こちらは削除してください。

2022-10-07 07:37 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +                )
encoder_az, encoder_el is not Noneではなく、"l_azやl_elのリストの長さが0でない"という評価に変更してください。

2022-10-07 07:51 UTC, FumikaDemachi requested changes
AntennaDeviceSimulatorの変更もお願いします。
現在はspeedをsubscribeしたら、エンコーダー値をpublishするという仕組みになっています。
一定時間で繰り返しエンコーダー値をpublishするように変更をお願いします。
[該当部分](https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/sim_devices.py#L24-L33)

具体的には、antenna_simulator関数の中身をself.enc.command(msg.az, "az")とself.enc.command(msg.el, "el")だけにし、[ここ](https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/sim_devices.py#L27-L33)を別の関数にしてtimerのコールバック関数にしてください。
timerの書き方は以下の[エンコーダーのスクリプト](https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/encoder.py#L21-L29)を参考にしてください。

2022-10-08 02:41 UTC, FumikaDemachi commented on necst/ctrl/antenna/sim_devices.py
> +        self.create_timer(timer_period, self.stream)
手元で動作確認をする時は今のようにtimer_periodを設定しても構いませんが、完成版をgitに挙げる時は`1 / config.antenna_command_frequency`としてください。

2022-10-08 02:42 UTC, FumikaDemachi commented on necst/ctrl/antenna/sim_devices.py
> +        self.create_subscription(TimedAzElFloat64, "speed", self.antenna_simulator, 1)
手元での動作確認の場合はこれでOKですが、完成版をgitに挙げる場合は`qos.realtime`にしてください。他の箇所も同様です。

2022-10-08 02:45 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        sub = self.node.create_subscription(CoordMsg, f"{ns}/encoder", update, 1)
手元での動作確認の場合はこれでOKですが、完成版をgitに挙げる場合は`qos.realtime`にしてください。

2022-10-08 02:46 UTC, FumikaDemachi commented on tests/ctrl/test_sim_devices.py
> +        #    print(msg)
必要ないコメントは消してください。

2022-10-08 02:57 UTC, FumikaDemachi requested changes
@takayama-27 
手元での動作確認用に変更した部分は、gitにあげる時には元に戻してください。

2022-10-08 17:35 UTC, KaoruNishikawa requested changes
@takayama-27 
細かい部分ですが、コメントした箇所だけ修正をお願いします。

2022-10-08 17:35 UTC, KaoruNishikawa commented on tests/ctrl/test_sim_devices.py
> +import pytest
import は空行を使って [標準ライブラリ](https://docs.python.org/ja/3/library/)、外部パッケージ、[同一パッケージ内](https://docs.python.org/ja/3/reference/import.html#package-relative-imports) の3グループに分けてほしいです。

```suggestion
import time

import pytest
```

2022-10-08 17:40 UTC, KaoruNishikawa commented on tests/ctrl/test_sim_devices.py
> +                el_condition = (len(l_el) != 0) and (l_el[0] < l_el[len(l_el) - 1])
```suggestion
                az_condition = (len(l_az) != 0) and (l_az[0] < l_az[-1])
                el_condition = (len(l_el) != 0) and (l_el[0] < l_el[-1])
```

2022-10-08 18:41 UTC, KaoruNishikawa approved these changes
LGTM!

2022-10-09 02:50 UTC, FumikaDemachi approved these changes
LGTM!

2022-10-09 13:43 UTC, merged