#29 pid制御
necst-telescope/necst pull request #58
Opened 2022-09-30 07:04 UTC by KKnapier

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #29

2022-09-30 07:35 UTC, FumikaDemachi commented on necst/core/recv_cmd.py
> +    node = Recorder()
Recorderをimportしてください。

2022-09-30 07:58 UTC, FumikaDemachi commented
@KKnapier 
PID計算に使う時刻を適切に選ぶことが目的なので、新しいファイルを作る必要はありません。
pid_controller.pyに書き加えてください。
[https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/pid_controller.py](url)

現在はpid_controller.pyの以下の箇所で、時刻を書き換えてしまっています。
時刻の書き換えを行う前にlistに加えて、calc_pid()内でそのlistから適切な時刻を採用するようにしましょう。
[https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/pid_controller.py#L44-L52](url)

2022-10-09 06:48 UTC, KaoruNishikawa requested changes
コメントした箇所について変更をお願いします。
(commit suggestion というボタンがあるコメントは、ボタンをクリックすることでそのままコミットできます)

2022-10-09 06:48 UTC, KaoruNishikawa commented on necst/ctrl/antenna/pid_controller.py
> +
```suggestion
        self.commands = []
```

2022-10-09 06:48 UTC, KaoruNishikawa commented on necst/ctrl/antenna/pid_controller.py
> +        enc = [msg.time, msg.lon, msg.lat]
```suggestion
```

2022-10-09 06:48 UTC, KaoruNishikawa commented on necst/ctrl/antenna/pid_controller.py
> +        cmd =[msg.time, msg.lon, msg.lat]
```suggestion
    def update_command(self, msg: CoordMsg) -> None:
        self.commands.append(msg)
```

2022-10-09 06:48 UTC, KaoruNishikawa commented on necst/ctrl/antenna/pid_controller.py
>          self.publisher.publish(msg)
以上の変更を行うと、`self.commands` にコマンド値が格納されます。
そこから時刻が適切なコマンドを選び、PID 計算に使用してください。

2022-10-15 13:46 UTC, KKnapier commented
まだエラーは直っていないのですが、for文の中身を見ていただきたいです。
イメージ的には時間の判定で全てのデータが未来の時刻を示さずにpopされリストの中身がなくなると考えたのですが、そんなことはありえませんか？
38行目辺りです。

2022-10-15 14:08 UTC, FumikaDemachi commented on necst/ctrl/antenna/pid_controller.py
> +                pass
```suggestion
        for i in range(len(sorted_list)):
            pop_msg = sorted_list.pop(0)
            if msg.time >= current:
                return msg.lon, msg.lat
        return None, None
```

2022-10-15 14:13 UTC, FumikaDemachi requested changes
for 文のところは、最後まで `msg.time >= current`を満たさなかったら`None`を返すようにすれば良いかと思います。
これで良いか確認してみてください。

2022-10-15 15:35 UTC, FumikaDemachi commented on necst/ctrl/antenna/pid_controller.py
> +            if msg.time >= current:
すみません、見落としていました。ここも修正してください。
```suggestion
            msg = sorted_list.pop(0)
            if msg.time >= current:
```

2022-10-15 15:38 UTC, FumikaDemachi requested changes
コメント箇所の修正をお願いします。

2022-10-16 13:39 UTC, FumikaDemachi commented on necst/ctrl/antenna/pid_controller.py
> +        for i in range(len(sorted_list)):
色々言ってすみません、こちらの方がわかりやすいかもしれません。
```suggestion
        while len(sorted_list)>0:
```

2022-10-20 04:25 UTC, FumikaDemachi approved these changes
LGTM !

2022-10-21 00:52 UTC, KaoruNishikawa commented on necst/ctrl/antenna/pid_controller.py
>          self.az = self.el = self.az_enc = self.el_enc = self.t = self.t_enc = None
@KKnapier 
`self.az`, `self.el`, `self.t` の値が更新されることがないように見えます。
値を更新するか、あるいはこれらのインスタンス変数を削除してください。

2022-10-21 03:55 UTC, KaoruNishikawa approved these changes
LGTM!

2022-10-21 03:55 UTC, merged