add thermometer_reader
necst-telescope/necst pull request #67
Opened 2022-10-14 08:14 UTC by takayama-27

**Checks**

- [x] Debugging completed
- [ ] Please debug me

**Related Issue**

This PR closes #63 

Thermometer()はまだ作っていませんが、temp、hum、pressを与える関数になる予定です。これらの値はself.thermo.read()で読めるようにする予定です。

2022-10-15 02:48 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +        self.publisher = self.create_publisher(Float64, "pressure", qos.realtime)
名前が被っているので、[リンク先](https://github.com/necst-telescope/necst/blob/main/necst/ctrl/antenna/motor.py)の書き方を参考にしてみてください。

2022-10-15 03:01 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +        th.start()
ROS2ではThreadではなく、timerを使うようにしてください。

2022-10-15 03:03 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +        self.publisher.publish(msg_press)
[こちら](https://github.com/necst-telescope/necst/pull/67/files#r996241908)と対応するように修正をお願いします。

2022-10-15 03:11 UTC, FumikaDemachi requested changes
@takayama-27 
コメントした箇所について確認をお願いします。

2022-10-17 07:55 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +        self.create_timer(1 / config.antenna_command_frequency, self.publisher)
```suggestion
        self.create_timer(1 / config.antenna_command_frequency, self.stream)
```

2022-10-20 01:02 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +import struct
使わないものは削除してください。

2022-10-20 03:19 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +from necst import namespace, qos, config
importの順番を[コードの書き方の箇所](https://github.com/necst-telescope/internal/discussions/2)を参照にして整理してください。

2022-10-21 16:46 UTC, takayama-27 commented
どこにエラーが出ているのかよくわかりません、、、

2022-10-22 14:42 UTC, FumikaDemachi commented on necst/ctrl/antenna/thermometer_reader.py
> +from pandas import Timedelta
使わないものは削除してください。

2022-10-24 01:57 UTC, FumikaDemachi requested changes
[ここ](https://github.com/necst-telescope/necst/blob/%2363_termometer_reader/necst/ctrl/antenna/__init__.py)に`from .thermometer_reader import ThermometerReader`も加えてください。

2022-10-24 11:59 UTC, FumikaDemachi approved these changes
LGTM !

2022-10-24 12:05 UTC, merged