#93-change namespace from antenna to ctrl
necst-telescope/necst pull request #97
Opened 2022-11-17 17:38 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #93

2022-11-17 17:54 UTC, KaoruNishikawa requested changes
@takayama-27 
座標計算でも気象計のデータを使っていたと思います。この変更が影響しないか確認してください。

2022-11-17 17:56 UTC, takayama-27 commented on necst/ctrl/antenna/thermometer_reader.py
> +    Namespace = namespace.ctrl
ではrootにしてしまいます。

2022-11-17 18:43 UTC, KaoruNishikawa requested changes

2022-11-17 18:43 UTC, KaoruNishikawa commented on necst/ctrl/antenna/horizontal_coord.py
> +            TimedFloat64, f"{namespace.ctrl}/humidity", callback_hum, qos.realtime
本当に `namespace.ctrl` で合っていますか？

2022-11-18 04:37 UTC, KaoruNishikawa approved these changes
LGTM!

2022-11-18 04:47 UTC, merged